[package]
name = "rowifi-database"
version = "1.0.0"
authors = ["Gautam.A <gautam.abhyankar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0"
mongodb = "1"
rowifi-models = { path = "../models" }
tracing = "0"
transient-dashmap = {branch = "main", git = "https://github.com/AsianIntel/transient-dashmap"}