[package]
name = "rowifi-database"
version = "3.0.0"
authors = ["Gautam.A <gautam.abhyankar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0"
mongodb = { branch = "master", git = "https://github.com/mongodb/mongo-rust-driver" }
rowifi-models = { path = "../models" }
rowifi-redis = { path = "../redis" }
tracing = "0"